defaults:
  - /preprocessing/encoder@encoder: null
  - /preprocessing/scaler@scaler: null
  - _self_

_target_: catboost.CatBoostClassifier

iterations: 300

learning_rate: 0.05

depth: 6

cat_features:
  - Embarked
  - Initial
  - Fare_cat
  - Pclass
  - Male

verbose: false

random_seed: ${seed}

is_cat: false

is_scale: false

calibration_method: ${tuning.calibration.method}

grid_params:
  model__iterations: [100, 150, 200]
  model__learning_rate: [0.01, 0.05, 0.1]
  model__depth: [3, 4, 6]