defaults:
  - /preprocessing/encoder@encoder: ordinal
  - /preprocessing/scaler@scaler: null
  - _self_

_target_: sklearn.tree.DecisionTreeClassifier

criterion: gini

max_depth: 8

random_state: ${seed}

is_cat: ${preprocessing.encode_categorical}

is_scale: false

grid_params:
  model__max_depth: [3, 5, 7]
  model__min_samples_split: [5, 20]
  model__min_samples_leaf: [2, 10]
  model__max_features: [null, "sqrt", "log2"]
  model__max_leaf_nodes: [null, 25, 50]