defaults:
  - /preprocessing/scaler@scaler: standard
  - /preprocessing/encoder@encoder: ohe
  - _self_

_target_: sklearn.neighbors.KNeighborsClassifier

n_neighbors: 5

weights: uniform

algorithm: auto

leaf_size: 30

p: 2

metric: minkowski

is_cat: ${preprocessing.encode_categorical}

is_scale: ${preprocessing.scale_numeric}

calibration_method: ${tuning.calibration.method}

grid_params:
  model__n_neighbors: [3, 5, 7, 9, 11, 13, 15, 17]
  model__weights: ["distance", "uniform"]
  model__leaf_size: [20, 30, 50]
  model__metric: ["cosine", "manhattan", "euclidean"]