defaults:
  - /preprocessing/scaler@scaler: standard
  - /preprocessing/encoder@encoder: ohe
  - _self_

_target_: sklearn.linear_model.LogisticRegression

penalty: l2

C: 1.0

l1_ratio: 0.0

solver: liblinear

tol: 0.0001

fit_intercept: true

max_iter: 1000

verbose: 0

scoring: accuracy

refit: true

Cs: 10

is_cat: ${preprocessing.encode_categorical}

is_scale: ${preprocessing.scale_numeric}

grid_params:
  model__C: [0.001, 0.01, 0.1, 1.0, 10.0, 100.0]
  model__penalty: ["l1", "l2"]
  model__solver: ["liblinear"]
  model__fit_intercept: [true, false]