defaults:
  - /preprocessing/encoder@encoder: ordinal
  - /preprocessing/scaler@scaler: minmax

is_cat: ${preprocessing.encode_categorical}

is_scale: ${preprocessing.scale_numeric}

epochs: 50

batch_size: 64

patience: 30

min_delta: 1e-5

shuffle: true

dropout_rate: 0.2

max_seq_len: 10

embedding_dim: 16

loss_function:
  _target_: torch.nn.BCELoss

optimizer:
  _target_: torch.optim.Adam
  lr: 0.01
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: 'min'
  patience: 5
  factor: 0.1

metrics:
  accuracy:
    _target_: torchmetrics.classification.BinaryAccuracy
  f1_score:
    _target_: torchmetrics.classification.BinaryF1Score
  precision:
    _target_: torchmetrics.classification.BinaryPrecision
  recall:
    _target_: torchmetrics.classification.BinaryRecall
