defaults:
  - data: titanic
  - training: default
  - preprocessing: default
  - tuning: default
  - logging: default
  - model@model.linear_model: linear_model
  - model@model.knn: knn
  - model@model.dt: dt
  - model@model.rf: rf
  - model@model.xgboost: xgboost
  - model@model.lightgbm: lightgbm
  - model@model.catboost: catboost
  - _self_

experiment_name: Titanic

target_column: Survived

seed: 42