defaults:
  - data: titanic
  - training: default
  - preprocessing: default
  - tuning: default
  - logging: default
  - solver: mapping
  - model@model.linear_model: linear_model
  - model@model.knn: knn
  - model@model.dt: dt
  - model@model.rf: rf
  - model@model.xgboost: xgboost
  - model@model.lightgbm: lightgbm
  - model@model.catboost: catboost
  - model@model.nn_model: nn_model
  - model@model.ensemble: ensemble
  - _self_

experiment_name: Titanic

target_column: Survived

seed: 42